### ISSUE TITLE
multi-label classification

### ISSUE THREAD

**Issue by bruffridge** [microsoft/ASTRA#3]
I read your paper, and was impressed by your approach. I'm considering using this approach for a multi-label classification problem I'm working on, but from the paper it seems that ASTRA is only doing multi-class classification. Do you know if it is possible to modify ASTRA to extract confidence scores for each class for each instance? My use-case involves generating a list of documents ranked by predicted similarity to a given class.

**Comment by gkaramanolakis** [comment]
The current version of ASTRA supports multi-class classification but it is possible to modify it for multi-label classification problems. 

In our [paper](https://aclanthology.org/2021.naacl-main.66.pdf), you would need to replace the loss functions for the Teacher and Student (Equations 1 and 4) with the corresponding multi-label versions. 

Our code directly provides access to the Teacher's probabilities (i.e., soft pseudo-labels instead of hard pseudo-labels) [here](https://github.com/microsoft/ASTRA/blob/fbda0d71549ab7befbe6e0427792b7ecbeae9aa9/astra/main.py#L127). You can use the Teacher's probabilities and define a multi-label loss as part of the Student's trainer code [here](https://github.com/microsoft/ASTRA/blob/fbda0d71549ab7befbe6e0427792b7ecbeae9aa9/astra/Student.py#L40). 

I hope this helps. :)
